### ISSUE TITLE
cant install v2

### ISSUE THREAD

**Issue by BladeFireLight** [jsabol/all-goblins-have-names#11]
installing from foundry vtt shows v2 but v1.3 is what get's installed.

**Comment by djmove1981** [comment]
Seconding this, even tried by coping the links directly instead of installing/updating for the modules managements and still gets stuck on 1.3.

**Comment by jsabol** [comment]
I forgot to update the version number in one spot! If it works, you're getting the latest version. I'll push a minor fix tonight so the version looks right. Thanks for flagging!!

**Comment by jsabol** [comment]
Fixed in version 2.0.1
